language: ruby
sudo: false
rvm:
- 2.3.3
- 2.4.0
- ruby-head
before_install:
- openssl aes-256-cbc -K $encrypted_be43a4149bae_key -iv $encrypted_be43a4149bae_iv
  -in aws_config.yml.enc -out spec/aws_config.yml -d
- openssl aes-256-cbc -K $encrypted_6dd48340d37f_key -iv $encrypted_6dd48340d37f_iv
  -in aws_config.yml.enc -out aws_config.yml -d
- gem install bundler
matrix:
  allow_failures:
  - rvm: ruby-head
env:
  global:
  - secure: GV7hFFW47ZPlB5Ws+yfDFP+3Z05769T2M/iggP/PFsGlfUzLRLgZsmxj72azNhkP3btiTZ0Ish8GOPoUPXb8ArVUMt4Ci9+f5JfWjXlNMWiga907GOIyAIskQsJN9UDlpcH5J49o1oL0APr74FB8pwFs5L+LiIdbUTHVZEQGWnM1kUkefWRS/WiawRL+p5WA8KJ+u3mwf+7yOmiS06OMzpU+1yjnZBTVg63EP0ejXoW59YpGMdNyYwWdZuisKbV3NgSSvVsRBszOxFpSAjzZIN618Nb3p0U4nVC13Dmk4ABp2pseBMrXPTTDPfHnEHdk4NPh1xQIfrTjiQqUXDeo5VhWnOZpjchUeBenJ6UpRwbuPcUNj7aNn6aVrjwNtEToKbWemXQAnwzl0fGR7308WICW3pmjQFjxNIbmFetZffCOU4IVI00RovcaFZnixqFDHH9xsHE3E5p2NRyGzSP1EtQ3UXKr+MjJVL6Uq5/WPFCDBTXznK8+xUoNTosx8cZVEzAQUY0pndOReueI4o1AIAZ+fkXKYUapG1oqRvfqpsBgjFD+IbqZiEiB+b0Bbx4PhS2ggx0dS9VUWhViIQBJJlcvZkY3NkWXpnNhGoY4v/VwJBf6qfRnkBVbmkFHnHGn3VzC8K0RjY9AEenym76AAXuo4gclRWYYq4aR99Qnp4E=
  - secure: ajYRGyBGlUDDUWU6yYryLSDOKcAKD61lrSZHMhvUGMN4wzdy9rSBAlXZM61eqi8DIalkB/3ClBO23ZRu5iK5uN6FWPYujQ1opcM4XkgWCJ/I8mS8F5Pjnwn/ghIPI8zLdfoqKwdSsKdgliQi2cgLvFdAUEKFjbxfTSYLXy6PgaH568whcrx9dwy+PBw/OExhqH1iUVoEV08IcDk4SY7frCWq9ax+We7g+KXrgZSSwuRRjgwQFN1ZZd/3qNnomZtkkk4GMZdSP2u29PGxr6511rPLqZ03dSiYyyyXoJnhOfRXhCFBIG18rcsApkX1/zjc4cPLUjSoJc6efSEJTKkl+Oil7vV1Tg5jLUY1H/4RgOhl94bhYnl0gS7liHNvFmqHajSVgdSiJhYbu5n0fhfp1NIKT1i/nqvbnkhvpxawxfiQ1507zduxIjr1N54SMMijQzcw/Oz86GgNZ1ZQhf4HUqBy5wN23FPsq2bS84ECAdIvQZuFoRSMfRC0kq9sflz+hvAa3pGbe8LwOR7wJyjNr4gXEWdPKhkSWhTn5XwIBUk8Gcqh8kHf0Uro7FjSSoTQqb8gw1dNVUXG1s2qlHTqBfK/Jlvo5JJLk5EJARFBo3IOpWqfcBpF7BHCEPi1r8htqP6zT1ejrE0G0pRy9wUcaLVnK+TgmTHTGiTWtd7UYG0=
